networkSettingValues = {"SERIES_PLAYBACK": [None, "SD", "HD"],
                        "SERIES_STOP": [None, 0, 1, 2, 5, 10, 15, 30, 60, 90, 120, 180],
                        "SERIES_SAVE_LATEST": [None, "ALL", 1, 2, 3, 4, 5],
                        "SERIES_OPTION": [None, "NEW", "ALL", "HOUR:MINUTE", "HOUR:MINUTE:DAY"],  # last 2... ?
                        "DVRPLUS_SERIES_SAVE": [None, "NEVER", "NEEDED"],  # change these too
                        "EPISODE_PLAYBACK": [None, "SD", "HD"],
                        "EPISODE_STOP": [None, 0, 1, 2, 5, 10, 15, 30, 60, 90, 120, 180],
                        "DVRPLUS_EPISODE_SAVE": [None, 1, 2, 7, 14, "NEVER", "NEEDED"]}  # last 2...?

recordRequestValues = {"REC_TYPE": [0, 1],
                       "STOP_TIME": [0, 60, 120, 300, 600, 900, 1800, 3600, 5400, 7200, 10800],
                       "SAVE_DAYS": [0, 1, 2, 7, 14, 98],
                       "QUALITY": ["SD", "HD"]}  # TODO finish dict

key_list = ["KEY_POWER",
            "KEY_A",
            "KEY_B",
            "KEY_C",
            "KEY_SETTINGS",
            "KEY_UP",
            "KEY_DOWN",
            "KEY_LEFT",
            "KEY_RIGHT",
            "KEY_SEL",
            "KEY_INFO",
            "KEY_GUIDE",
            "KEY_EXIT",
            "KEY_LAST",
            "KEY_MENU",
            "KEY_VOL_UP",
            "KEY_VOL_DOWN",
            "KEY_MUTE",
            "KEY_CH_UP",
            "KEY_CH_DOWN",
            "KEY_DVR",
            "KEY_LIVE",
            "KEY_PLAY",
            "KEY_REPLAY",
            "KEY_PAUSE",
            "KEY_REC",
            "KEY_1",
            "KEY_2",
            "KEY_3",
            "KEY_4",
            "KEY_5",
            "KEY_6",
            "KEY_7",
            "KEY_8",
            "KEY_9",
            "KEY_0"]
